### PR TITLE
Added a suggestion for hosting an event.

### PR DESCRIPTION
**Pull request by saifeemustafaq**
Added a link to the workshop I generally conduct for pre-final year students to prepare them for their interview. This workshop counts as a project in their resume and the project itself is resume building.

### CODE REVIEW

**Comment by jimbobbennett** [comment]
Thanks for your contribution!

Can you make the format of it match the other entries - so the link in the header and a brief description underneath. Can you also add a 🇬🇧emoji to indicate the post is in English.

I'm going to work through the post today and will provide feedback before merging this.

**Comment by jimbobbennett** [comment]
This is a great blog post! A nice workshop for students to do.

Some feedback on the blog post:

* You mention both the student and normal free offers in the Microsoft Account configuration section, but only the normal free offer in th lets start section. Might be worth adding the student offer here as students may start there to sign up.
* Same with the link to join GitHub - if the target is students then maybe link to the student developer pack as well as creating an account. The student developer pack will also give them the student azure subscription.
* The Azure portal has changed since this was written - there is no hamburger menu (three lines) any more. Can you update the pics and text to reflect this
* The app service tier that is the default is $73 a month! 😲 I would suggest they use the free app service tier otherwise they'll use up the $100 of student credit in 6 weeks

**Comment by saifeemustafaq** [comment]
@jimbobbennett Just a remider, is there anything else I should add?

**Comment by jimbobbennett** [comment]
Apologies @saifeemustafaq - this repo has been under a bit of restructuring the last few weeks adding back content that we removed thinking it wasn't needed. Got a few more PRs to get in, then I'll merge this in.

**Comment by saifeemustafaq** [comment]
Alright. Let me know if my help is needed in any other repository or writing stuff.

**Comment by jimbobbennett** [comment]
Sorry - been taking a while to overhaul things and fix issues. I've raised a new PR #278 for this after manually copying over the link.

**Pull request closed without merging**
